# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Nuestro Encuentro"
  url = "#encuentro"
  weight = 10
  
[[main]]
  name = "Faculty"
  url = "#people"
  weight = 20

[[main]]
  name = "Research"
  url = "#grupos"
  weight = 30

[[main]]
  name = "Publications"
  url = "#publicaciones"
  weight = 40

[[main]]
  name = "Olimpiadas"
  url = "#olimpiadas"
  weight = 60

[[main]]
  name = "Círculos"
  url = "#circulos"
  weight = 50

[[main]]
  name = "Alumni"
  url = "#alumni"
  weight = 70

[[main]]
  name = "Evento"
  url = "#NoArquimediano"
  weight = 5

[[main]]
  name = "Contact us"
  url = "#contact"
  weight = 100


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
